/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module MyMC14495 (
  input D3,
  input D2,
  input D1,
  input D0,
  input point,
  input LE,
  output a,
  output d,
  output c,
  output f,
  output e,
  output g,
  output b,
  output p
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  assign s3 = ~ D3;
  assign s0 = ~ D2;
  assign s1 = ~ D1;
  assign s2 = ~ D0;
  assign p = ~ point;
  assign a = (((D0 & s1 & D2 & D3) | (D0 & D1 & s0 & D3) | (s2 & s1 & D2 & s3) | (D0 & s1 & s0 & s3)) | LE);
  assign d = (((s2 & D1 & s0 & D3) | (D0 & D1 & D2) | (s2 & s1 & D2 & s3) | (D0 & s1 & s0 & s3)) | LE);
  assign c = (((D1 & D2 & D3) | (s2 & D2 & D3) | (s2 & D1 & s0 & s3)) | LE);
  assign f = (((D0 & s1 & D2 & D3) | (D0 & D1 & s3) | (D1 & s0 & s3) | (D0 & s0 & s3)) | LE);
  assign e = (((D0 & s1 & s0) | (s1 & D2 & s3) | (D0 & s3)) | LE);
  assign g = (((s2 & s1 & D2 & D3) | (D0 & D1 & D2 & s3) | (s1 & s0 & s3)) | LE);
  assign b = (((D0 & D1 & D3) | (s2 & D2 & D3) | (s2 & D1 & D2) | (D0 & s1 & D2 & s3)) | LE);
endmodule
