/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module Adder1b (
  input A,
  input B,
  input C,
  output S,
  output Co
);
  assign S = ((A ^ B) ^ C);
  assign Co = ((A & B) | (A & C) | (B & C));
endmodule

module Adder4b (
  input Ci,
  input [3:0] A,
  input [3:0] B,
  output [3:0] S,
  output Co
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  assign s0 = A[0];
  assign s4 = A[1];
  assign s8 = A[2];
  assign s12 = A[3];
  assign s1 = B[0];
  assign s5 = B[1];
  assign s9 = B[2];
  assign s13 = B[3];
  Adder1b Adder1b_i0 (
    .A( s0 ),
    .B( s1 ),
    .C( Ci ),
    .S( s2 ),
    .Co( s3 )
  );
  Adder1b Adder1b_i1 (
    .A( s4 ),
    .B( s5 ),
    .C( s3 ),
    .S( s6 ),
    .Co( s7 )
  );
  Adder1b Adder1b_i2 (
    .A( s8 ),
    .B( s9 ),
    .C( s7 ),
    .S( s10 ),
    .Co( s11 )
  );
  Adder1b Adder1b_i3 (
    .A( s12 ),
    .B( s13 ),
    .C( s11 ),
    .S( s14 ),
    .Co( Co )
  );
  assign S[0] = s2;
  assign S[1] = s6;
  assign S[2] = s10;
  assign S[3] = s14;
endmodule
