/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module Adder1b (
  input A,
  input B,
  input C,
  output S,
  output Co
);
  assign S = ((A ^ B) ^ C);
  assign Co = ((A & B) | (A & C) | (B & C));
endmodule

module AddSub1b (
  input A,
  input B,
  input Ctrl,
  input Ci,
  output S,
  output Co
);
  wire s0;
  assign s0 = (B ^ Ctrl);
  Adder1b Adder1b_i0 (
    .A( A ),
    .B( s0 ),
    .C( Ci ),
    .S( S ),
    .Co( Co )
  );
endmodule
