/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module Adder1b (
  input A,
  input B,
  input C,
  output S,
  output Co
);
  assign S = ((A ^ B) ^ C);
  assign Co = ((A & B) | (A & C) | (B & C));
endmodule

module AddSub1b (
  input A,
  input B,
  input Ctrl,
  input Ci,
  output S,
  output Co
);
  wire s0;
  assign s0 = (B ^ Ctrl);
  Adder1b Adder1b_i0 (
    .A( A ),
    .B( s0 ),
    .C( Ci ),
    .S( S ),
    .Co( Co )
  );
endmodule

module AddSub4b (
  input Ctrl,
  input [3:0] A,
  input [3:0] B,
  output [3:0] S,
  output Co
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  assign s0 = A[0];
  assign s1 = A[1];
  assign s2 = A[2];
  assign s3 = A[3];
  assign s4 = B[0];
  assign s5 = B[1];
  assign s6 = B[2];
  assign s7 = B[3];
  AddSub1b AddSub1b_i0 (
    .A( s0 ),
    .B( s4 ),
    .Ctrl( Ctrl ),
    .Ci( Ctrl ),
    .S( s8 ),
    .Co( s9 )
  );
  AddSub1b AddSub1b_i1 (
    .A( s1 ),
    .B( s5 ),
    .Ctrl( Ctrl ),
    .Ci( s9 ),
    .S( s10 ),
    .Co( s11 )
  );
  AddSub1b AddSub1b_i2 (
    .A( s2 ),
    .B( s6 ),
    .Ctrl( Ctrl ),
    .Ci( s11 ),
    .S( s12 ),
    .Co( s13 )
  );
  AddSub1b AddSub1b_i3 (
    .A( s3 ),
    .B( s7 ),
    .Ctrl( Ctrl ),
    .Ci( s13 ),
    .S( s14 ),
    .Co( Co )
  );
  assign S[0] = s8;
  assign S[1] = s10;
  assign S[2] = s12;
  assign S[3] = s14;
endmodule
