/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module D_FlipFlop (
  input D,
  input C_p,
  input S_bar,
  input R_bar,
  output Q,
  output Q_bar
);
  wire s0;
  wire s1;
  wire s2;
  wire Q_bar_temp;
  wire Q_temp;
  assign s1 = ~ (~ (S_bar & s0 & s1) & R_bar & C_p);
  assign s2 = ~ (s1 & C_p & s0);
  assign s0 = ~ (s2 & D & R_bar);
  assign Q_temp = ~ (S_bar & s1 & Q_bar_temp);
  assign Q_bar_temp = ~ (Q_temp & s2 & R_bar);
  assign Q = Q_temp;
  assign Q_bar = Q_bar_temp;
endmodule
