/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module D_Latch (
  input D,
  input C,
  output Q,
  output Q_bar
);
  wire Q_temp;
  wire Q_bar_temp;
  assign Q_temp = ~ (~ (D & C) & Q_bar_temp);
  assign Q_bar_temp = ~ (Q_temp & ~ (C & ~ D));
  assign Q = Q_temp;
  assign Q_bar = Q_bar_temp;
endmodule
