/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module D_74LS138 (
  input C,
  input B,
  input A,
  input G,
  input G2A,
  input G2B,
  output [7:0] Y
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  assign s0 = ~ C;
  assign s1 = ~ B;
  assign s2 = ~ A;
  assign s6 = (B & C);
  assign s7 = ~ (G2A | ~ G | G2B);
  assign s3 = (s0 & s1);
  assign s4 = (C & s1);
  assign s5 = (s0 & B);
  assign Y[0] = ~ (s3 & s2 & s7);
  assign Y[1] = ~ (s4 & s2 & s7);
  assign Y[2] = ~ (s5 & s2 & s7);
  assign Y[3] = ~ (s6 & s2 & s7);
  assign Y[4] = ~ (A & s3 & s7);
  assign Y[5] = ~ (s4 & A & s7);
  assign Y[6] = ~ (s5 & A & s7);
  assign Y[7] = ~ (s6 & A & s7);
endmodule

module LampCtrl138 (
  input S1,
  input S2,
  input S3,
  output F
);
  wire [7:0] s0;
  D_74LS138 D_74LS138_i0 (
    .C( S1 ),
    .B( S2 ),
    .A( S3 ),
    .G( 1'b1 ),
    .G2A( 1'b0 ),
    .G2B( 1'b0 ),
    .Y( s0 )
  );
  assign F = ~ (s0[1] & s0[2] & s0[4] & s0[7]);
endmodule
