/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module light_1 (
  input S1,
  input S2,
  input S3,
  output F
);
  assign F = ((S1 & ~ S2 & ~ S3) | (~ S1 & S2 & ~ S3) | (~ S1 & ~ S2 & S3) | (S1 & S2 & S3));
endmodule
