/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module Real_Gated_SR_Latch (
  input R,
  input S,
  input C,
  output Q,
  output Q_bar
);
  wire Q_temp;
  wire Q_bar_temp;
  assign Q_temp = ~ (~ (S & C) & Q_bar_temp);
  assign Q_bar_temp = ~ (Q_temp & ~ (C & R));
  assign Q = Q_temp;
  assign Q_bar = Q_bar_temp;
endmodule

module MS_SR_FlipFlop (
  input S,
  input C,
  input R,
  output Q,
  output Q_bar
);
  wire s0;
  wire s1;
  wire s2;
  Real_Gated_SR_Latch Real_Gated_SR_Latch_i0 (
    .R( R ),
    .S( S ),
    .C( C ),
    .Q( s0 ),
    .Q_bar( s1 )
  );
  assign s2 = ~ C;
  Real_Gated_SR_Latch Real_Gated_SR_Latch_i1 (
    .R( s1 ),
    .S( s0 ),
    .C( s2 ),
    .Q( Q ),
    .Q_bar( Q_bar )
  );
endmodule
