/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module Real_Gated_SR_Latch (
  input R,
  input S,
  input C,
  output Q,
  output Q_bar
);
  wire Q_temp;
  wire Q_bar_temp;
  assign Q_temp = ~ (~ (S & C) & Q_bar_temp);
  assign Q_bar_temp = ~ (Q_temp & ~ (C & R));
  assign Q = Q_temp;
  assign Q_bar = Q_bar_temp;
endmodule
