/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module SR_Latch (
  input R,
  input S,
  output Q,
  output Q_bar
);
  wire Q_bar_temp;
  wire Q_temp;
  assign Q_temp = ~ (R | Q_bar_temp);
  assign Q_bar_temp = ~ (Q_temp | S);
  assign Q = Q_temp;
  assign Q_bar = Q_bar_temp;
endmodule
