/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module D_Latch (
  input D,
  input C,
  output Q,
  output Q_bar
);
  wire Q_temp;
  wire Q_bar_temp;
  assign Q_temp = ~ (~ (D & C) & Q_bar_temp);
  assign Q_bar_temp = ~ (Q_temp & ~ (C & ~ D));
  assign Q = Q_temp;
  assign Q_bar = Q_bar_temp;
endmodule

module D_Latch_Flip (
  input EN,
  input C,
  output Q,
  output Q_bar
);
  wire Q_bar_temp;
  wire s0;
  assign s0 = (Q_bar_temp & EN);
  D_Latch D_Latch_i0 (
    .D( s0 ),
    .C( C ),
    .Q( Q ),
    .Q_bar( Q_bar_temp )
  );
  assign Q_bar = Q_bar_temp;
endmodule
