/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module Adder1b (
  input A,
  input B,
  input C,
  output S,
  output Co
);
  assign S = ((A ^ B) ^ C);
  assign Co = ((A & B) | (A & C) | (B & C));
endmodule

module AddSub1b (
  input A,
  input B,
  input Ctrl,
  input Ci,
  output S,
  output Co
);
  wire s0;
  assign s0 = (B ^ Ctrl);
  Adder1b Adder1b_i0 (
    .A( A ),
    .B( s0 ),
    .C( Ci ),
    .S( S ),
    .Co( Co )
  );
endmodule

module AddSub4b (
  input Ctrl,
  input [3:0] A,
  input [3:0] B,
  output [3:0] S,
  output Co
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  assign s0 = A[0];
  assign s1 = A[1];
  assign s2 = A[2];
  assign s3 = A[3];
  assign s4 = B[0];
  assign s5 = B[1];
  assign s6 = B[2];
  assign s7 = B[3];
  AddSub1b AddSub1b_i0 (
    .A( s0 ),
    .B( s4 ),
    .Ctrl( Ctrl ),
    .Ci( Ctrl ),
    .S( s8 ),
    .Co( s9 )
  );
  AddSub1b AddSub1b_i1 (
    .A( s1 ),
    .B( s5 ),
    .Ctrl( Ctrl ),
    .Ci( s9 ),
    .S( s10 ),
    .Co( s11 )
  );
  AddSub1b AddSub1b_i2 (
    .A( s2 ),
    .B( s6 ),
    .Ctrl( Ctrl ),
    .Ci( s11 ),
    .S( s12 ),
    .Co( s13 )
  );
  AddSub1b AddSub1b_i3 (
    .A( s3 ),
    .B( s7 ),
    .Ctrl( Ctrl ),
    .Ci( s13 ),
    .S( s14 ),
    .Co( Co )
  );
  assign S[0] = s8;
  assign S[1] = s10;
  assign S[2] = s12;
  assign S[3] = s14;
endmodule

module Mux4to1b4 (
  input [3:0] I0,
  input [3:0] I1,
  input [3:0] I2,
  input [3:0] I3,
  input [1:0] S,
  output [3:0] O
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  assign s3 = S[0];
  assign s5 = S[1];
  assign s7 = (s5 & s3);
  assign s0 = ~ s3;
  assign s1 = ~ s5;
  assign s2 = (s0 & s1);
  assign s4 = (s3 & s1);
  assign s6 = (s0 & s5);
  assign O[0] = ((s2 & I0[0]) | (s4 & I1[0]) | (s6 & I2[0]) | (s7 & I3[0]));
  assign O[1] = ((s2 & I0[1]) | (s4 & I1[1]) | (s6 & I2[1]) | (s7 & I3[1]));
  assign O[2] = ((s2 & I0[2]) | (s4 & I1[2]) | (s6 & I2[2]) | (s7 & I3[2]));
  assign O[3] = ((s2 & I0[3]) | (s4 & I1[3]) | (s6 & I2[3]) | (s7 & I3[3]));
endmodule

module Mux4to1 (
  input [1:0] S,
  input [3:0] I,
  output O
);
  assign O = (((~ S[0] & ~ S[1]) & I[0]) | ((S[0] & ~ S[1]) & I[1]) | ((~ S[0] & S[1]) & I[2]) | ((S[1] & S[0]) & I[3]));
endmodule

module MyALU (
  input [1:0] S,
  input [3:0] A,
  input [3:0] B,
  output Co,
  output [3:0] C
);
  wire [3:0] s0;
  wire [3:0] s1;
  wire s2;
  wire [3:0] s3;
  wire s4;
  wire [3:0] s5;
  assign s0 = (A & B);
  assign s1 = (A | B);
  assign s4 = S[0];
  AddSub4b AddSub4b_i0 (
    .Ctrl( s4 ),
    .A( A ),
    .B( B ),
    .S( s5 ),
    .Co( s2 )
  );
  assign s3[0] = s2;
  assign s3[1] = s2;
  assign s3[2] = 1'b0;
  assign s3[3] = 1'b0;
  Mux4to1b4 Mux4to1b4_i1 (
    .I0( s5 ),
    .I1( s5 ),
    .I2( s0 ),
    .I3( s1 ),
    .S( S ),
    .O( C )
  );
  Mux4to1 Mux4to1_i2 (
    .S( S ),
    .I( s3 ),
    .O( Co )
  );
endmodule
