/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module Mux_2x1
(
    input [0:0] sel,
    input in_0,
    input in_1,
    output reg out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule

module DIG_D_FF_1bit
#(
    parameter Default = 0
)
(
   input D,
   input C,
   output Q,
   output \~Q
);
    reg state;

    assign Q = state;
    assign \~Q = ~state;

    always @ (posedge C) begin
        state <= D;
    end

    initial begin
        state = Default;
    end
endmodule


module shift_reg9b (
  input clk,
  input S_L,
  input [8:0] P_in,
  input S_in,
  output [8:0] Q
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire s16;
  wire s17;
  wire s18;
  wire s19;
  wire s20;
  wire s21;
  wire s22;
  wire s23;
  wire s24;
  wire s25;
  wire s26;
  assign s9 = P_in[0];
  assign s25 = P_in[1];
  assign s7 = P_in[2];
  assign s4 = P_in[3];
  assign s1 = P_in[4];
  assign s21 = P_in[5];
  assign s18 = P_in[6];
  assign s15 = P_in[7];
  assign s12 = P_in[8];
  Mux_2x1 Mux_2x1_i0 (
    .sel( S_L ),
    .in_0( S_in ),
    .in_1( s9 ),
    .out( s10 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i1 (
    .D( s10 ),
    .C( clk ),
    .Q( s23 )
  );
  Mux_2x1 Mux_2x1_i2 (
    .sel( S_L ),
    .in_0( s23 ),
    .in_1( s25 ),
    .out( s26 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i3 (
    .D( s26 ),
    .C( clk ),
    .Q( s6 )
  );
  Mux_2x1 Mux_2x1_i4 (
    .sel( S_L ),
    .in_0( s6 ),
    .in_1( s7 ),
    .out( s8 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i5 (
    .D( s8 ),
    .C( clk ),
    .Q( s3 )
  );
  Mux_2x1 Mux_2x1_i6 (
    .sel( S_L ),
    .in_0( s3 ),
    .in_1( s4 ),
    .out( s5 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i7 (
    .D( s5 ),
    .C( clk ),
    .Q( s0 )
  );
  Mux_2x1 Mux_2x1_i8 (
    .sel( S_L ),
    .in_0( s0 ),
    .in_1( s1 ),
    .out( s2 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i9 (
    .D( s2 ),
    .C( clk ),
    .Q( s20 )
  );
  Mux_2x1 Mux_2x1_i10 (
    .sel( S_L ),
    .in_0( s20 ),
    .in_1( s21 ),
    .out( s22 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i11 (
    .D( s22 ),
    .C( clk ),
    .Q( s17 )
  );
  Mux_2x1 Mux_2x1_i12 (
    .sel( S_L ),
    .in_0( s17 ),
    .in_1( s18 ),
    .out( s19 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i13 (
    .D( s19 ),
    .C( clk ),
    .Q( s14 )
  );
  Mux_2x1 Mux_2x1_i14 (
    .sel( S_L ),
    .in_0( s14 ),
    .in_1( s15 ),
    .out( s16 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i15 (
    .D( s16 ),
    .C( clk ),
    .Q( s11 )
  );
  Mux_2x1 Mux_2x1_i16 (
    .sel( S_L ),
    .in_0( s11 ),
    .in_1( s12 ),
    .out( s13 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i17 (
    .D( s13 ),
    .C( clk ),
    .Q( s24 )
  );
  assign Q[0] = s23;
  assign Q[1] = s6;
  assign Q[2] = s3;
  assign Q[3] = s0;
  assign Q[4] = s20;
  assign Q[5] = s17;
  assign Q[6] = s14;
  assign Q[7] = s11;
  assign Q[8] = s24;
endmodule
